pipeline {
    agent any

   stages {
        stage('Build') {
            steps {
                sh '''
                    echo $PARAM_STRING
                    sleep 5
                '''
            }
        }

        stage('Test') {
            steps {
                script {
                    echo "${params.PARAM_STRING}"
                }
            }
        }

    }
}